### ISSUE TITLE
Could you make the transition speed adjustable?

### ISSUE THREAD

**Issue by fbegue** [akshay9/react-3d-cube-transition#1]
really cool library! 

I'm also having trouble running your example in codesandbox:
https://codesandbox.io/s/react-3d-cube-transition-test-rb9lr

thanks

**Comment by akshay9** [comment]
Thank you @fbegue for reporting the bug.
I have fixed it in new 1.0.4 release
https://codesandbox.io/s/react-3d-cube-transition-test-forked-ck59w

I'll add an option for editing the transition speed in the next release asap.

**Comment by akshay9** [comment]
Transition speed can now be adjusted using `animationDuration` Prop available in the v1.0.5.

Thanks for using the library.
